# This is the name of the workflow, visible on GitHub UI
name: Compile Library's Examples
on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.h'
      - '**CompileLibraryExamples.yml'
  pull_request:

jobs:
  build:
    name: Compile for ${{ matrix.arduino-platform }}

    # Target OS
    runs-on: ubuntu-20.04

    env:
      # Comma separated list without double quotes around the list
      REQUIRED_LIBRARIES:

    strategy:
      # The Matrix contains all the configuration to be tested. For each configuration, all the examples are tested
      matrix:

        # A couple of configuration for testing the library
        arduino-platform:
          # The oldest version compatible with RTCMemory 2.x
          - esp8266:esp8266@2.6.0
          # The newest version compatible with RTCMemory 2.x
          - esp8266:esp8266@3.0.2

        platform-url:
          - https://arduino.esp8266.com/stable/package_esp8266com_index.json
        # In arduino-boards-fqbn you can specify additional hardware parameters,
        # like clock frequency or partition scheme
        # Type "arduino-cli board listall" to view the available boards
        arduino-boards-fqbn: 
          - esp8266:esp8266:generic
            
      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    # This is the list of steps this job will run
    steps:

      # clone the repo using the `checkout` action
      - name: Checkout
        uses: actions/checkout@v2

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update

      - name: Compile all examples using the arduino-test-compile action
        # Specify the git tag, not the Github release
        uses: ArminJo/arduino-test-compile@v3.2.0
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          arduino-platform: ${{ matrix.arduino-platform }}
          platform-url: ${{ matrix.platform-url }}
